(defun layout:make-viewport (layout pt-center width height pt-model pt2)
    "从模型空间生成布局"
    (entmakex (list (quote (0 . "viewport"))
            (quote (100 . "acdbentity"))
            (quote (67 . 1))
            (cons 410 layout)
            (quote (100 . "acdbviewport"))
            (cons 10 pt-center)
            (cons 40 width)
            (cons 41 height)
            (quote (68 . 2))
            (quote (69 . 2))
            (cons 12 pt-model)
            (quote (13 0.0 0.0 0.0))
            (quote (14 0.5 0.5 0.0))
            (quote (15 0.5 0.5 0.0))
            (quote (16 0.0 0.0 1.0))
            (quote (17 6.0 4.5 -6.89434))
            (quote (42 . 50.0))
            (quote (43 . 0.0))
            (quote (44 . 0.0))
            (quote (45 . 1.79005e+006))
            (quote (50 . 0.0))
            (quote (51 . 0.0))
            (quote (72 . 1))
            (quote (90 . 819296))
            (quote (281 . 0))
            (quote (71 . 1))
            (quote (74 . 0))
            (quote (110 0.0 0.0 0.0))
            (quote (111 1.0 0.0 0.0))
            (quote (112 0.0 1.0 0.0))
            (quote (79 . 0))
            (quote (146 . 0.0))
            (quote (170 . 0))
            (quote (61 . 5))
            (quote (292 . 1))
            (quote (282 . 1))
            (quote (141 . 0.0))
            (quote (142 . 0.0))
            (quote (63 . 250)))))
